spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/block_board?serverTimezone=UTC&characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://localhost:3306/block_board?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: blockboard
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true
  resource:
    static-locations : classpath:/static/
    add-mappings : true
  mustache:
    cache: false
  output:
    ansi:
      enabled: always

mybatis:
  type-aliases-package: com.board.project.blockboard.mapper
  mapper-locations: mybatis/mapper/**/*.xml
server:
  servlet:
    session:
      persistent: true
  error:
    whitelabel:
      enabled: false

# SQL Log 볼 때 사용하는 옵션
#logging:
#  level:
#    jdbc.sqlonly: info
#    org.springframework.web: DEBUG
#    com.zaxxer.hikari.HikariDataSource: warn