spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  type-aliases-package: com.board.project.blockboard.mapper
  mapper-locations: mybatis/mapper/**/*.xml
server:
  error:
    whitelabel:
      enabled: false

